import numpy as np
from hmmlearn import hmm
import warnings

# Suppress ConvergenceWarnings from hmmlearn for short windows
# warnings.filterwarnings("ignore", category=ConvergenceWarning)

class MarketRegimeHMM:
    """
    Hidden Markov Model (HMM) for detecting 4 market regimes:
    0: trend-positive
    1: trend-negative
    2: mean-reverting (low-vol)
    3: high-volatility

    Inputs for Emission (features):
    [log_return, norm_volume, relative_spread]
    """
    
    def __init__(self, n_regimes: int = 4, random_state: int = 42):
        self.n_regimes = n_regimes
        self.model = hmm.GaussianHMM(
            n_components=n_regimes,
            covariance_type="diag",  # Diagonal covariance: always positive-definite, robust on short windows
            n_iter=100,
            tol=0.01,
            random_state=random_state,
            min_covar=1e-3,  # Extra regularization to prevent near-zero diagonal variances
        )
        self.is_fitted = False

    def _prepare_features(self, prices: np.ndarray, volumes: np.ndarray, spreads: np.ndarray) -> np.ndarray:
        """
        Calculates required emission features mathematically.
        Input shapes expected: (N_ticks,)
        """
        if len(prices) < 2:
            raise ValueError("Require at least 2 ticks to compute log returns.")
            
        # Log returns r_t = ln(P_t/P_{t-1})
        log_returns = np.zeros_like(prices)
        log_returns[1:] = np.log(prices[1:] / prices[:-1])
        log_returns[0] = 0.0 # First tick has 0 return
        
        # Normalize volume roughly to [0, ~3] via z-score or max proxy to avoid extreme values
        v_mean = np.mean(volumes) + 1e-8
        v_std = np.std(volumes) + 1e-8
        norm_volumes = (volumes - v_mean) / v_std
        
        # Relative Spread = spread_absolute / mid_price
        rel_spreads = spreads / (prices + 1e-8)
        
        # Combine into matrix (N_samples, n_features=3)
        features = np.column_stack([log_returns, norm_volumes, rel_spreads])
        
        # Replace extreme outliers / NaNs generated by bad data
        features = np.nan_to_num(features, nan=0.0, posinf=5.0, neginf=-5.0)
        return features

    def train(self, prices: np.ndarray, volumes: np.ndarray, spreads: np.ndarray):
        """Fits the Gaussian HMM onto the historical window features."""
        X = self._prepare_features(prices, volumes, spreads)
        self.model.fit(X)
        self.is_fitted = True

    def predict_regime_probabilities(self, prices: np.ndarray, volumes: np.ndarray, spreads: np.ndarray) -> np.ndarray:
        """
        Estimates the probability distribution over the 4 hidden states for the LATEST tick.
        Input seq should be a short recent window (e.g., last 100 ticks).
        Returns: np.ndarray of shape (4,) containing probabilities summing to 1.
        """
        if not self.is_fitted:
            raise RuntimeError("HMM model must be fitted with `train()` before predicting.")
            
        X = self._prepare_features(prices, volumes, spreads)
        
        # Computes posterior probabilities of being in each hidden state
        # given the observations up to time T.
        # Shape: (n_samples, n_components)
        try:
            posteriors = self.model.predict_proba(X)
            # We only care about the latest state estimation
            latest_probabilities = posteriors[-1]
        except (ValueError, np.linalg.LinAlgError):
            # Numerical failure (e.g. singular covariance on short windows) -> uniform distribution
            latest_probabilities = np.ones(self.n_regimes) / self.n_regimes
            return latest_probabilities

        # Clip numerical inaccuracies keeping strictly bounded
        latest_probabilities = np.clip(latest_probabilities, 0.0, 1.0)
        total = np.sum(latest_probabilities)
        if total <= 0:
            return np.ones(self.n_regimes) / self.n_regimes
        latest_probabilities /= total
        
        return latest_probabilities

# --- Design Decisions Note ---
# 1. Used Full Gaussian Covariance allowing the features (price, vol, spread) to correlate freely, which is critical in market microstructure (e.g., high volatility correlates with large spreads).
# 2. Used trailing normalization for volumes to ensure the emission matrices do not explode.
# 3. Model returns `.predict_proba()` latest vector element guarantees output format exactly `(4,)` mapping to the MarketMakingEnv Space.
